version: "3.9"

services:
  isotrainer:
    build: .
    image: isotrainer-web:latest
    container_name: isotrainer-web
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.isotrainer.rule=Host(`isotrainer.cstera.alphaomegahealth.com.br`)"
      - "traefik.http.routers.isotrainer.entrypoints=https"
      - "traefik.http.routers.isotrainer.tls=true"
      - "traefik.http.routers.isotrainer.tls.certresolver=cloudflare"
      - "traefik.http.services.isotrainer.loadbalancer.server.port=80"
      - "traefik.http.middlewares.isotrainer-auth.basicauth.users=usuario:$$2y$$05$$g6qPfLxiRzCy7HQIxuNdYe7tdbljjwEpDSqecbgqyH6rfTOkgcKAe"
      - "traefik.http.routers.isotrainer.middlewares=isotrainer-auth"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
